name: Github Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/checkout@v3

      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install Android SDK tools
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sudo apt-get update
          yes | sudo apt-get install unzip

      - name: Install build-tools 34.0.0
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          sdkmanager --install "build-tools;34.0.0"


      - name: Install build-tools 34.0.0
        run: sdkmanager "build-tools;34.0.0"

      - name: Verify build-tools version
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "Using build-tools version: $BUILD_TOOL_VERSION"

      - name: Convert Keystore to JKS (if needed)
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-keystore.p12
          keytool -importkeystore \
            -srckeystore my-keystore.p12 \
            -srcstoretype PKCS12 \
            -destkeystore my-keystore.jks \
            -deststoretype JKS \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build APK
        id: build
        run: bash ./gradlew assembleTempoRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/tempo/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS_GITHUB }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD_GITHUB }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Make artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ github.ref }}
          body: '> Changelog coming soon'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{steps.sign_apk.outputs.signedReleaseFile}}
          asset_name: app-tempo-release.apk
          asset_content_type: application/zip
